name: production
run-name: Production workflow
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    
jobs:
    # Build app with gradle
    build:
        name: Build app and setup gradle
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
                java-version: '17'
                distribution: 'temurin'
                         
          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
            with:
                gradle-version: '8.5'
          - name: Build with Gradle 8.5
            run: gradle build
    
    # Create a new release
    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Publish package
              run: |
                cd ${{ github.workspace }}
                gradle publish
              env:
                  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        