name: production
run-name: Production workflow
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    
jobs:
    # Build app with gradle
    build:
        name: Build app and setup gradle
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
                java-version: '17'
                distribution: 'temurin'
                         
          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
            with:
                gradle-version: '8.5'
                
          - name: Setup xvfb for screen 0 and build with Gradle
            run: Xvfb :1 -screen 0 1600x1200x24 &
          - run: gradle build
            env:
                DISPLAY: :1
          - name: Tear down xvfb
            run: killall Xvfb
            
          - name: Publish package
            run: gradle publish
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
                  